namespace RetroFront.Models.ScreenScraper.System
{
    public class Media
    {
        public string type { get; set; }
        public string parent { get; set; }
        public string url { get; set; }
        public string region { get; set; }
        public string crc { get; set; }
        public string md5 { get; set; }
        public string sha1 { get; set; }
        public string format { get; set; }
        public string posx { get; set; }
        public string posy { get; set; }
        public string posw { get; set; }
        public string posh { get; set; }
        public string ssx { get; set; }
        public string ssy { get; set; }
        public string ssw { get; set; }
        public string ssh { get; set; }
        public string ssrotation { get; set; }
        public string sstitlex { get; set; }
        public string sstitley { get; set; }
        public string sstitlew { get; set; }
        public string sstitleh { get; set; }
        public string sstitlerotation { get; set; }
        public string wheelx { get; set; }
        public string wheely { get; set; }
        public string wheelw { get; set; }
        public string wheelh { get; set; }
        public string wheelrotation { get; set; }
        public string titrex { get; set; }
        public string titrey { get; set; }
        public string titrew { get; set; }
        public string titreh { get; set; }
        public string titretypo { get; set; }
        public string titrerotation { get; set; }
        public string titretyposizemax { get; set; }
        public string titrecouleur { get; set; }
        public string titreMaj { get; set; }
        public string descriptionx { get; set; }
        public string descriptiony { get; set; }
        public string descriptionw { get; set; }
        public string descriptionh { get; set; }
        public string descriptiontypo { get; set; }
        public string descriptionrotation { get; set; }
        public string descriptiontyposizemax { get; set; }
        public string descriptioncouleur { get; set; }
        public string descriptionMaj { get; set; }
        public string Titrecouleur { get; set; }
        public string TitreMaj { get; set; }
        public string destavantx { get; set; }
        public string destavanty { get; set; }
        public string destavantw { get; set; }
        public string destavanth { get; set; }
        public string avantpers { get; set; }
        public string destcotex { get; set; }
        public string destcotey { get; set; }
        public string destcotew { get; set; }
        public string destcoteh { get; set; }
        public string cotepers { get; set; }
        public string rotation { get; set; }
        public string avantx { get; set; }
        public string avanty { get; set; }
        public string avantw { get; set; }
        public string avanth { get; set; }
        public string cotex { get; set; }
        public string cotey { get; set; }
        public string cotew { get; set; }
        public string coteh { get; set; }
        public string version { get; set; }
        public string rbctrlid { get; set; }
        public string supportx { get; set; }
        public string supporty { get; set; }
        public string supportw { get; set; }
        public string supporth { get; set; }
    }
}
