// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetroFront.DataAccess;

namespace RetroFront.DataAccess.Migrations
{
    [DbContext(typeof(AppSQLIteContext))]
    [Migration("20210109184811_Initialization")]
    partial class Initialization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("RetroFront.Models.Emulator", b =>
                {
                    b.Property<int>("EmulatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SystemeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmulatorID");

                    b.HasIndex("SystemeID");

                    b.ToTable("Emulators");
                });

            modelBuilder.Entity("RetroFront.Models.Game", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Boxart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dev")
                        .HasColumnType("TEXT");

                    b.Property<string>("Editeur")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmulatorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fanart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("GameID");

                    b.HasIndex("EmulatorID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RetroFront.Models.Systeme", b =>
                {
                    b.Property<int>("SystemeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<string>("Shortname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .HasColumnType("TEXT");

                    b.HasKey("SystemeID");

                    b.ToTable("Systemes");
                });

            modelBuilder.Entity("RetroFront.Models.Emulator", b =>
                {
                    b.HasOne("RetroFront.Models.Systeme", "Systeme")
                        .WithMany("Emulators")
                        .HasForeignKey("SystemeID");

                    b.Navigation("Systeme");
                });

            modelBuilder.Entity("RetroFront.Models.Game", b =>
                {
                    b.HasOne("RetroFront.Models.Emulator", null)
                        .WithMany("Games")
                        .HasForeignKey("EmulatorID");
                });

            modelBuilder.Entity("RetroFront.Models.Emulator", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("RetroFront.Models.Systeme", b =>
                {
                    b.Navigation("Emulators");
                });
#pragma warning restore 612, 618
        }
    }
}
